-- Creation of database, schema and tables

-- Database: nrpjdzzp

CREATE DATABASE nrpjdzzp
    WITH
    OWNER = nrpjdzzp
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE nrpjdzzp TO nrpjdzzp;


-- SCHEMA: flights

CREATE SCHEMA FLIGHTS;


CREATE TABLE FLIGHTS.FLT_PILOT
(
    PILOT_ID BIGINT NOT NULL,
    PILOT_NAME character varying(50),
    CONSTRAINT PILOT_ID_PKEY PRIMARY KEY (PILOT_ID)
);

CREATE TABLE FLIGHTS.FLT_AIRPLANE
(
    AIRPLANE_ID BIGINT NOT NULL,
    AIRPLANE_NAME character varying(20),
    CONSTRAINT AIRPLANE_ID_PKEY PRIMARY KEY (AIRPLANE_ID)
);

CREATE TABLE FLIGHTS.FLT_FLIGHT
(
    FLIGHT_ID BIGINT NOT NULL,
    FLIGHT_CODE character varying(10),
    FLIGHT_START timestamp,
    FLIGHT_END timestamp,
    FLIGHT_STATUS INTEGER,
    FLIGHT_PILOT_ID BIGINT NOT NULL,
    FLIGHT_AIRPLANE_ID BIGINT NOT NULL,
    CONSTRAINT FLIGHT_ID_PKEY PRIMARY KEY (FLIGHT_ID),

    CONSTRAINT FLIGHT_PILOT_ID_FKEY FOREIGN KEY (FLIGHT_PILOT_ID)
        REFERENCES FLIGHTS.FLT_PILOT (PILOT_ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT FLIGHT_AIRPLANE_ID_FKEY FOREIGN KEY (FLIGHT_AIRPLANE_ID)
        REFERENCES FLIGHTS.FLT_AIRPLANE (AIRPLANE_ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

